# Color Filtering using HSV
In the make_blue challenge, we were operating in the BGR "colorspace" (Blue, Green, Red), but there are other colorspaces -- including HSV (hue, saturation, value).  HSV is also three values, but they operate differently.

You can get an idea by looking at this diagram:

![HSV Color wheel](https://upload.wikimedia.org/wikipedia/commons/0/0d/HSV_color_solid_cylinder_alpha_lowgamma.png)

The first step in leveraging HSV is to convert the image into the HSV colorspace...  Let's use our favorite image and convert to to HSV and see what it looks like.  We'll load up the image and display it standard first.

In [17]:
import cv2
import numpy as np
import os

def load_image_file(image_file):        # I used a function here to combine the test with the load
    if(os.path.isfile(image_file)):     # os.path.isfile returns true if the file exists, why is this needed?
	    img = cv2.imread(image_file)
    else:
	    print("Invalid file, exiting....")
	    exit(1)
    return(img)

team_image_file = "..\..\images\Jagbots2017.jpg"

team_image_BGR = load_image_file(team_image_file)

cv2.imshow("Image", team_image_BGR)                          # this function will open a window with the image
cv2.waitKey(0)                                    # this function will wait until a key is pressed
    
cv2.destroyAllWindows()


So we've loaded it up, now let's convert it to the HSV colorspace.  This next snippet requires that the above code has been run, so be sure you ran it!

We're going to create a new image in the HSV colorspace.  This conversion is similar to converting to Grayscale, but it produces an image that is color, but not the same colors...

In [ ]:
# convert from BGR to HSV
#
team_image_HSV = cv2.cvtColor(team_image_BGR, cv2.COLOR_BGR2HSV)

cv2.imshow("HSV Image", team_image_HSV)
cv2.waitKey(0)

cv2.destroyAllWindows()

If it all worked correctly, you're seeing a pretty different image -- like one that was taken using a nuclear camera flash.

Obviously we are not doing this to make it prettier to human eyes -- so why bother?  We convert to HSV for the same reason we will often convert to Grayscale, it makes it easier to perform other operations -- like color filtering.

Since we are going to be chasing the reflective tape used by FIRST, let's switch to a sample image from last season...

In [18]:
import cv2
import numpy as np
import os

def load_image_file(image_file):        # I used a function here to combine the test with the load
    if(os.path.isfile(image_file)):     # os.path.isfile returns true if the file exists, why is this needed?
	    img = cv2.imread(image_file)
    else:
	    print("Invalid file, exiting....")
	    exit(1)
    return(img)

image_file = "../../images/tape_sample_images/sample7.png"

image_BGR = load_image_file(image_file)

cv2.imshow("Image", image_BGR)                  # this function will open a window with the image
cv2.waitKey(0)                                  # this function will wait until a key is pressed
    

# convert from BGR to HSV
#
image_HSV = cv2.cvtColor(image_BGR, cv2.COLOR_BGR2HSV)

cv2.imshow("HSV Image", image_HSV)
cv2.waitKey(0)

cv2.destroyAllWindows()

Looking at these images, you get an idea of why that tape is so special -- it really stands out.  Now let's try to filter for that color...

In [19]:
# define range of green color in HSV
lower_tape = np.array([50,90,110])
upper_tape = np.array([100,255,255])

# Threshold the HSV image to get only blue colors
mask = cv2.inRange(image_HSV, lower_tape, upper_tape)

# Bitwise-AND mask and original image
res = cv2.bitwise_and(image_BGR,image_BGR, mask= mask)

cv2.imshow('image',image_BGR)
cv2.imshow('mask',mask)
cv2.imshow('res',res)

# Let's define our kernel size
kernel = np.ones((5,5), np.uint8)

# Now we erode
erosion = cv2.erode(res, kernel, iterations = 1)
cv2.imshow('Erosion', erosion)

cv2.waitKey(0)

cv2.destroyAllWindows()

Let's find the rectangles

In [21]:
# Grayscale
gray = cv2.cvtColor(erosion,cv2.COLOR_BGR2GRAY)

# Find Canny edges
edged = cv2.Canny(gray, 30, 200)
cv2.imshow('Canny Edges', edged)
cv2.waitKey(0)

# Finding Contours
# Use a copy of your image e.g. edged.copy(), since findContours alters the image
_, contours, hierarchy = cv2.findContours(edged, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cv2.imshow('Canny Edges After Contouring', edged)
cv2.waitKey(0)

print("Number of Contours found = " + str(len(contours)))

# Draw all contours
# Use '-1' as the 3rd parameter to draw all
cv2.drawContours(image_BGR, contours, -1, (0,255,0), 3)

cv2.imshow('Contours', image_BGR)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of Contours found = 2


In [32]:
# print(contours[0][0])
print(np.amin(contours[0],0))
print(np.amax(contours[0],0))
print(np.amin(contours[1],0))
print(np.amax(contours[1],0))
# print(contours[0][-1])
# print(contours[0])
# let's verify
contourOne = contours[0]
print(np.amin(contourOne[0]))
print(np.amax(contourOne[0]))
print(np.amin(contourOne[1]))
print(np.amax(contourOne[1]))

print(contourOne)
dir(contours)

[[574 470]]
[[598 532]]
[[466 468]]
[[489 532]]
470
576
484
576
[[[576 470]]

 [[576 484]]

 [[575 485]]

 [[575 509]]

 [[574 510]]

 [[574 512]]

 [[575 513]]

 [[575 523]]

 [[574 524]]

 [[574 530]]

 [[575 531]]

 [[587 531]]

 [[588 532]]

 [[595 532]]

 [[595 522]]

 [[596 521]]

 [[596 518]]

 [[597 517]]

 [[597 482]]

 [[598 481]]

 [[598 477]]

 [[597 476]]

 [[597 474]]

 [[598 473]]

 [[598 471]]

 [[586 471]]

 [[585 470]]]


['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

# Working with numpy arrays
The contours data is in an array, but not a standard python array -- it is an ndarray from the numpy package.  Arrays are kind of what numpy is about, so it's worth exploring them a bit.  We want to use the contours data for two purposes:
1.  determine position relative to the camera's orientation
2.  determine (relative) distance

In theory, if we can do that, we know the direction and distance the robot must travel to reach the target.

Let's see what we can get from the numpy array, starting with how many dimensions it has -- using ndarray.ndim

We have this code in our script:
```python
_, contours, hierarchy = cv2.findContours(edged, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
```
This code finds "contours" (think shapes defined by continuous edges) in the image.  There are three things returned, an actual image, which we don't need, so we assign it to "_" (this tells python to throw it away).  The second is "contours" -- which is a list of numpy arrays (yeah, lots going on here...)

What this means is that to use the numpy array functions (like ndim), we will need to pull items from the list...

(for convenience, I'm going to pull the code from above into a single cell, so you don't have to run every cell)

In [9]:
import cv2
import numpy as np
import os

def load_image_file(image_file):        # I used a function here to combine the test with the load
    if(os.path.isfile(image_file)):     # os.path.isfile returns true if the file exists, why is this needed?
	    img = cv2.imread(image_file)
    else:
	    print("Invalid file, exiting....")
	    exit(1)
    return(img)

# this sample has "lit up" reflective tape
#
image_file = "../../images/tape_sample_images/sample7.png"

image_BGR = load_image_file(image_file)

# convert from BGR to HSV
image_HSV = cv2.cvtColor(image_BGR, cv2.COLOR_BGR2HSV)

# define range of green color in HSV
lower_tape = np.array([50,90,110])
upper_tape = np.array([100,255,255])

# Threshold the HSV image to get only the tape
mask = cv2.inRange(image_HSV, lower_tape, upper_tape)

# Bitwise-AND mask and original image
res = cv2.bitwise_and(image_BGR,image_BGR, mask= mask)

cv2.imshow('res',res)

# Erosion -- will get rid of some of the "noise".  We are looking for big objects -- small pixel stuff
#            is probably just "noise".  Erosion will remove smaller details
#
# Let's define our kernel size - impacts the extent of the removal
#
kernel = np.ones((5,5), np.uint8)

# Now we erode
erosion = cv2.erode(res, kernel, iterations = 1)
cv2.imshow('Erosion', erosion)

cv2.waitKey(0)

cv2.destroyAllWindows()

# Grayscale
gray = cv2.cvtColor(erosion,cv2.COLOR_BGR2GRAY)

# Find Canny edges
edged = cv2.Canny(gray, 30, 200)
cv2.imshow('Canny Edges', edged)
cv2.waitKey(0)

# Finding Contours
# Use a copy of your image e.g. edged.copy(), since findContours alters the image
_, contours, hierarchy = cv2.findContours(edged, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cv2.imshow('Canny Edges After Contouring', edged)
cv2.waitKey(0)

print("Number of Contours found = " + str(len(contours)))

# Draw all contours
# Use '-1' as the 3rd parameter to draw all
cv2.drawContours(image_BGR, contours, -1, (0,255,0), 3)

cv2.imshow('Contours', image_BGR)
cv2.waitKey(0)
cv2.destroyAllWindows()

###
# NEW CODE STARTS HERE
###

for contour in contours:
    print(contour.ndim)
    print(contour.shape)
    print(contour[0])
    

Number of Contours found = 2
3
(27, 1, 2)
3
(18, 1, 2)


In [44]:
from typing import NamedTuple

foundShapes = []

class Shape(NamedTuple):
    min_pt: tuple
    max_pt: tuple
    width: int
    height: int

for i, contour in enumerate(contours):
    print(f"Contour #{i}")
    print(contour.ndim)
    print(contour.shape)
    
    minPoint = np.amin(contour,0)[0]
    maxPoint = np.amax(contour,0)[0]
    
    print(f"minPoint {minPoint}, maxPoint {maxPoint}")
    
    width = maxPoint[0]-minPoint[0]
    height = maxPoint[1]-minPoint[1]
    
    shape = Shape(minPoint,maxPoint,width,height)
    foundShapes.append(shape)
    print(f"width {width}, height {height}")
    
for shape in foundShapes:
    print(shape)

completeShape=np.vstack((foundShapes[0].min_pt,foundShapes[1].min_pt,foundShapes[0].max_pt,foundShapes[1].max_pt))
print(completeShape)

min_pt=np.amin(completeShape,0)
max_pt=np.amax(completeShape,0)

print(f"Complete Shape:  min {min_pt}, max {max_pt}")


Contour #0
3
(27, 1, 2)
minPoint [574 470], maxPoint [598 532]
width 24, height 62
Contour #1
3
(18, 1, 2)
minPoint [466 468], maxPoint [489 532]
width 23, height 64
Shape(min_pt=array([574, 470], dtype=int32), max_pt=array([598, 532], dtype=int32), width=24, height=62)
Shape(min_pt=array([466, 468], dtype=int32), max_pt=array([489, 532], dtype=int32), width=23, height=64)
[[574 470]
 [466 468]
 [598 532]
 [489 532]]
Complete Shape:  min [466 468], max [598 532]


In [51]:
# Let's find the center of two points in our shape

def findCenterPt(min_pt, max_pt):
    x_coord = int(((max_pt[0]-min_pt[0])/2)+min_pt[0])
    y_coord = int(((max_pt[1]-min_pt[1])/2)+min_pt[1])
    
    centerPt = np.array([x_coord,y_coord])
    return(centerPt)


centerPt = findCenterPt(min_pt,max_pt)

print(f"Center Point is {centerPt}")

centerTgtImage = cv2.circle(image_BGR, tuple(centerPt), 10, (0,0,255),-1)

cv2.imshow("Target Acquired", centerTgtImage)
cv2.waitKey(0)

cv2.destroyAllWindows()

Center Point is [532 500]
